In [101]:
import numpy as np
import tensorflow as tf
import pandas as pd

In [18]:

tf.Variable(np.random.normal(size=(10,1)), name='reg_W')

<tf.Variable 'reg_W_2:0' shape=(10, 1) dtype=float64_ref>

In [8]:
a.shape

(10, 1)

In [11]:
dtype(a)

NameError: name 'dtype' is not defined

In [53]:
n_items = 100
batch_size = 5
batches = int(n_items/batch_size)
print(batch_size, batches)
for i in range(batches):
    ixs = range(batch_size*i,batch_size*(i+1))
    

5 20


In [54]:
X = np.random.normal(size=(1000,5))

In [63]:
X[95:100,:]

array([[-1.37198015, -1.32822019, -0.10708998,  0.28442609,  0.33679303],
       [ 1.28097427, -1.6812042 ,  0.06137967,  0.59301105,  0.36377688],
       [ 0.64372783, -0.90347066,  2.8509946 ,  0.07883244,  0.63433562],
       [-2.30879706,  0.85575004,  0.82029442, -0.53760201,  0.43178382],
       [-0.98362479,  1.52844178,  0.58639998,  1.44467245, -0.86053376]])

In [57]:
X[ixs,:]

array([[-1.37198015, -1.32822019, -0.10708998,  0.28442609,  0.33679303],
       [ 1.28097427, -1.6812042 ,  0.06137967,  0.59301105,  0.36377688],
       [ 0.64372783, -0.90347066,  2.8509946 ,  0.07883244,  0.63433562],
       [-2.30879706,  0.85575004,  0.82029442, -0.53760201,  0.43178382],
       [-0.98362479,  1.52844178,  0.58639998,  1.44467245, -0.86053376]])

In [58]:
ixs

range(95, 100)

In [150]:
for i in range(10):
    b = np.ones((20,1))*i
    if i == 0:
        bs = b
    bs = np.append(bs,b,axis=0)

In [151]:
bs.shape

(220, 1)

In [152]:
a = bs.squeeze()

In [146]:
pd.Series(a)

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ... 
215    9.0
216    9.0
217    9.0
218    9.0
219    9.0
Length: 220, dtype: float64

In [83]:
np.squeeze(b).shape

(20,)

In [105]:
b.squeeze()

array([9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9.,
       9., 9., 9.])

In [103]:
c = pd.Series(b.squeeze())

In [108]:
c.append(b.squeeze())

TypeError: cannot concatenate object of type '<class 'numpy.ndarray'>'; only Series and DataFrame objs are valid